# Generated by Django 3.1.3 on 2020-12-17 00:40

from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('info', models.TextField(max_length=100, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('info', models.TextField(max_length=100, null=True)),
                ('avatar', models.ImageField(null=True, upload_to=mysite.models.user_avatar_path)),
            ],
        ),
        migrations.CreateModel(
            name='UserToGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linked_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.group')),
                ('linked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.user')),
            ],
        ),
        migrations.CreateModel(
            name='UpdToExp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linked_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.experiment')),
                ('linked_upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.update')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField()),
                ('data', models.FileField(upload_to=mysite.models.user_data_path)),
                ('file_type', models.CharField(max_length=6, null=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.user')),
            ],
        ),
        migrations.AddField(
            model_name='update',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.user'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('answer_date', models.DateTimeField(auto_now=True)),
                ('answer_info', models.TextField()),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.user')),
                ('target_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.update')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mysite.user'),
        ),
        migrations.CreateModel(
            name='ExpToGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linked_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.experiment')),
                ('linked_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.group')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.user'),
        ),
        migrations.CreateModel(
            name='DataToUpd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linked_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.updatedata')),
                ('linked_upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.update')),
            ],
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField()),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.user')),
                ('upd1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update1', to='mysite.update')),
                ('upd2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update2', to='mysite.update')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField()),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.user')),
                ('target_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.update')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('reply_time', models.DateTimeField(auto_now=True)),
                ('reply', models.BooleanField(default=False)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.user')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.group')),
            ],
        ),
    ]
