# Generated by Django 3.1.4 on 2020-12-16 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField(max_length=100, null=True)),
                ('avatar', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=1)),
                ('django_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='apply',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_creator', to='mysite.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_creator', to='mysite.userprofile'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compare_creator', to='mysite.userprofile'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exp_creator', to='mysite.userprofile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='group_master', to='mysite.userprofile'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_creator', to='mysite.userprofile'),
        ),
        migrations.AlterField(
            model_name='update',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_creator', to='mysite.userprofile'),
        ),
        migrations.AlterField(
            model_name='updatedata',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_creator', to='mysite.userprofile'),
        ),
        migrations.AlterField(
            model_name='usertogroup',
            name='linked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.userprofile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
