# Generated by Django 3.1.3 on 2020-12-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='name',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='update',
            name='name',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='updatedata',
            name='name',
            field=models.TextField(default='default'),
        ),
    ]
