# Generated by Django 3.1.3 on 2020-12-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='imgs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
