# Generated by Django 3.1.3 on 2020-12-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20201219_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='imgs',
            field=models.TextField(default=''),
        ),
    ]
