# Generated by Django 3.1.4 on 2020-12-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20201216_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
