# Generated by Django 3.1.3 on 2020-12-22 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_compare_imgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMPComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField()),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmp_comment_creator', to='mysite.userprofile')),
                ('target_cmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.compare')),
            ],
        ),
    ]
