# Generated by Django 3.1.3 on 2020-12-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_cmpcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='imgs',
            field=models.TextField(default=''),
        ),
    ]
