# Generated by Django 3.1.3 on 2020-12-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20201223_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='answer_info',
            field=models.TextField(default=''),
        ),
    ]
